name: preview
on:
  push:
    branches:
      - master

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 22
  

      - name: Setup EAS
        uses: expo/expo-github-action@v9
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun
          eas-cache: true

      - name: Install dependencies
        run: bun install

      - name: Create update
        uses: expo/expo-github-action/preview@v9
        with:
          command: eas update --auto
